# Generated by Django 4.0.4 on 2022-06-02 10:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(null=True, unique=True, verbose_name='room_number')),
                ('room_number_en', models.PositiveIntegerField(null=True, unique=True, verbose_name='room_number')),
                ('room_number_ru', models.PositiveIntegerField(null=True, unique=True, verbose_name='room_number')),
                ('room_number_uz', models.PositiveIntegerField(null=True, unique=True, verbose_name='room_number')),
                ('is_busy', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_busy')),
                ('is_busy_en', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_busy')),
                ('is_busy_ru', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_busy')),
                ('is_busy_uz', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_busy')),
                ('about', ckeditor.fields.RichTextField(verbose_name='about')),
                ('about_en', ckeditor.fields.RichTextField(null=True, verbose_name='about')),
                ('about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='about')),
                ('about_uz', ckeditor.fields.RichTextField(null=True, verbose_name='about')),
                ('booking_from_time', models.DateTimeField(blank=True, null=True, verbose_name='booking_from_time')),
                ('booking_from_time_en', models.DateTimeField(blank=True, null=True, verbose_name='booking_from_time')),
                ('booking_from_time_ru', models.DateTimeField(blank=True, null=True, verbose_name='booking_from_time')),
                ('booking_from_time_uz', models.DateTimeField(blank=True, null=True, verbose_name='booking_from_time')),
                ('booking_until_time', models.DateTimeField(blank=True, null=True, verbose_name='booking_until_time')),
                ('booking_until_time_en', models.DateTimeField(blank=True, null=True, verbose_name='booking_until_time')),
                ('booking_until_time_ru', models.DateTimeField(blank=True, null=True, verbose_name='booking_until_time')),
                ('booking_until_time_uz', models.DateTimeField(blank=True, null=True, verbose_name='booking_until_time')),
                ('type_of_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Room.typeofroommodel', verbose_name='type')),
                ('type_of_room_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Room.typeofroommodel', verbose_name='type')),
                ('type_of_room_ru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Room.typeofroommodel', verbose_name='type')),
                ('type_of_room_uz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Room.typeofroommodel', verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='images/', verbose_name='images')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.roommodel', verbose_name='room_id')),
            ],
        ),
    ]
