# Generated by Django 4.0.4 on 2022-06-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Lux', 'Lux'), ('Business', 'Business'), ('Actual', 'Actual')], max_length=100)),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('type_of_booking', models.CharField(choices=[('Booking daily', 'Daily'), ('Booking hourly', 'Hourly')], max_length=100)),
                ('room_date', models.DateField()),
                ('sum_of_people', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
